name: Integration tests

on: push

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Fake running tests
        run: echo "Am running tests yo!"
