pretext: Triggered via {{eventName}} of {{env.VERSION}} by {{actor}}
title: "Project {{env.VERSION}} release"
title_link: {{repositoryUrl}}/{{env.VERSION}}

text: >
  {{#if (eq jobStatus "SUCCESS")}}
    {{icon jobStatus}} Project {{env.VERSION}} has been released :rocket:
  {{else if (eq jobStatus "FAILURE")}}
    {{icon jobStatus}} Project {{env.VERSION}} release failed!
  {{else if (eq jobStatus "CANCELLED")}}
    {{icon jobStatus}} Project {{env.VERSION}} release has been cancelled!
  {{/if}}

fallback: |-
  [GitHub] Project {{env.VERSION}} release status is {{jobStatus}}

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> <{{workflowRunUrl}}|{{workflow}} #{{runNumber}}>

colors:
  success: "#5DADE2"
  failure: "#884EA0"
  cancelled: "#A569BD"
  default: "#7D3C98"

icons:
  success: ":white_check_mark:"
  failure: ":x:"
  cancelled: ":interrobang:"
  skipped: ":interrobang:"
  default: ":interrobang:"
