pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{actionRef}}
title: "Project {{actionRef}} release"
title_link: "{{repositoryUrl}}/{{actionRef}}"

text: >
  {{icon jobStatus}}
  {{#if (eq jobStatus "SUCCESS")}}
    Project {{actionRef}} has been released :rocket:
  {{else if (eq jobStatus "FAILURE")}}
    Project {{actionRef}} release failed!
  {{else if (eq jobStatus "CANCELLED")}}
    Project {{actionRef}} release has been cancelled!
  {{/if}}

fallback: |-
  [GitHub] {{repositoryName}} {{actionRef}} release is {{jobStatus}}

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> <{{workflowRunUrl}}|{{workflow}} #{{runNumber}}>

colors:
  success: "#5DADE2"
  failure: "#884EA0"
  cancelled: "#A569BD"
  default: "#7D3C98"

icons:
  success: ":white_check_mark:"
  failure: ":x:"
  cancelled: ":interrobang:"
  skipped: ":interrobang:"
  default: ":interrobang:"
