pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
title: "Project {{ref}} release"
title_link: "{{refUrl}}"

text: |
  {{icon jobStatus}}
  {{#if (eq jobStatus "SUCCESS")}}
    {{repositoryName}} {{ref}} has been released :rocket:
  {{else if (eq jobStatus "FAILURE")}}
    {{repositoryName}} {{ref}} release failed!
  {{else if (eq jobStatus "CANCELLED")}}
    {{repositoryName}} {{ref}} release has been cancelled!
  {{/if}}

fallback: |-
  [GitHub] {{repositoryName}} {{ref}} release is {{jobStatus}}

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

icons:
  success: ":white_check_mark:"
  failure: ":x:"
  cancelled: ":interrobang:"
  skipped: ":interrobang:"
  default: ":interrobang:"
