pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
title: "{{icon jobStatus}} {{repositoryName}} {{ref}} release"
title_link: "{{refUrl}}"

text: |
  {{icon jobStatus}}
  {{#if (eq jobStatus "success")}}
    {{repositoryName}} {{ref}} has been released :rocket:
  {{else if (eq jobStatus "failure")}}
    {{repositoryName}} {{ref}} release failed!
  {{else if (eq jobStatus "cancelled")}}
    {{repositoryName}} {{ref}} release has been cancelled!
  {{/if}}

fallback: |-
  [GitHub] {{repositoryName}} {{ref}} release is {{jobStatus}}

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}
