name: build

on:
  push:
    branches:
      - master

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: "install tox"
        run: pip3 install tox

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: "install tox here too"
        run: |
          pip3 install -U setuptools
          pip3 install tox
