name: build

on:
  push:
    branches:
      - master


jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - run: MY_VAR="FOO"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job

    steps:
      - run: echo $FOO
      - run: echo ${{ env.FOO }}


