name: build

on:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create some files
        run: |
          mkdir dist
          touch dist/foo.tar.gz
          touch dist/bar.tar.gz
          touch dist/foo.zip
          touch dist/foo-checksums.txt

      - name: SHOW ME!
        run: ls dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*checksums.txt
