name: build

on:
  push:
    branches:
      - master


jobs:
  cacher:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: mkdir -p path/to/cache

    - uses: actions/cache@v1
      id: my-cache
      with:
        path: path/to/cache
        key: ${{ runner.os }}-${{ hashFiles('**') }}

    - name:
      # Skips step if cache is valid
      if: steps.my-cache.outputs.cache-hit == false
      run: echo hello > path/to/cache/world.txt

