name: build

on:
  push:
    branches:
      - master


jobs:
  cacher:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: mkdir -p path/to/output

    - name: Generate something
      # Skips step if cache is valid
      run:
        echo hello >> path/to/output/greetings.txt
        echo world >> path/to/output/greetings.txt

    - name: Upload greetings
      uses: actions/upload-artifact@v1
      with:
        name: greetings
        path: path/to/output/greetings.txt

  windows-runner:
    runs-on: windows-latest
    needs: cacher

    steps:
      - name: Download greetings
        uses: actions/download-artifact@v1
        with:
          name: greetings

      - name: Print it
        shell: python
        run: |
          print(open("greetings", "r").read())
          print("on Windows")


  ubuntu-runner:
    runs-on: ubuntu-latest
    needs: cacher

    steps:
      - name: Download greetings
        uses: actions/download-artifact@v1
        with:
          name: greetings

      - name: Print it
        shell: python
        run: |
          print(open("greetings", "r").read())
          print("on Ubuntu")