name: build

on: [pull_request]

jobs:
  files-check:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.check.outputs.result }}

    steps:
      - name: Checks edited files
        id: check
        uses: actions/github-script@v2
        with:
          result-encoding: string
          script: |
            const result = await github.pulls.listFiles({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
              per_page: 100
            })
            console.log(result.data)
            const changed = result.data.filter(f => !f.filename.startsWith("docs/"))
              .filter(f => f.filename !== ".github/workflows/docs.yaml").length > 0
            console.log("changed", changed)
            return changed

  test-matrix:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    needs: files-check
    if: needs.files-check.outputs.result == false

    steps:
      - name: Checkout
        # if: needs.files-check.outputs.result == false
        uses: actions/checkout@master

      - name: Prints system
        # if: needs.files-check.outputs.result == false
        run: echo ${{ matrix.operating-system }}

      - name: Prints previous jobs output
        # if: needs.files-check.outputs.result == false
        run: echo ${{ needs.files-check.outputs.result }}
