name: build

on:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prints things
        run: |
          echo "${{ github.workflow }}"
          echo "${{ github.event_name}}"
          echo "${{ github.event.pull_request.number }}"
          echo "${{ github.event.number }}"
          echo "${{ github.sha }}"
