name: build

on:
  push:
    branches:
      - master


jobs:
  centos-6-build:
    runs-on: ubuntu-latest
    container: centos:centos6

    steps:
      - uses: actions/setup-node
        with:
          node-version: '11.x'

      - uses: actions/checkout@v2
        with:
          # Fetches only one commit
         fetch-depth: 1

