name: build

on:
  pull_request:

jobs:
  test-matrix:
    name: Tests
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prints system
        run: echo ${{ matrix.operating-system }}

  uploader:
    name: Uploads artifact
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - name: Create a file
        run: touch my-artifact

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: my-artifact
