name: build

on:
  push

jobs:
  does-things:
    name: Does things
    runs-on: windows-latest

    steps:
      - name: Dir current
        run: dir

      - name: Dir C:\
        run: cd C:\ && dir
