name: Issues test

on:
  issues:
    types: [opened, labeled]

jobs:
  test-issue:
    if: >
      github.event.action == 'opened' ||
      (github.event.action == 'labeled' &&
      contains(github.event.issue.labels.*.name, 'foo'))
    runs-on: ubuntu-latest

    steps:
      - name: Prints data
        run: |
          echo ${{ github.event.action }}
          echo ${{ github.event.issue.title}}
          echo ${{ github.event.issue.body }}
          echo ${{ github.event.issue.html_url }}

      - name: Some more data
        run: |
          echo ${{ github.event.issue.labels.*.name }}
          echo "here we are"
