name: Do something after merge

on:
  push:
    branches:
      - master
    paths:
      - "**.txt"

jobs:
  pushed:
    runs-on: ubuntu-latest
    outputs:
      modified_matrix: ${{ steps.sync.output.modified_matrix }}
      deleted_matrix: ${{ steps.sync.output.deleted_matrix }}
      any_modified: ${{ steps.files.outputs.any_modified }}
      any_deleted: ${{ steps.files.outputs.any_deleted }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # With the default value of 1, there are corner cases where tj-actions/changed-files
          # fails with a `no merge base` error
          fetch-depth: 0

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v34
        with:
          json: true
          files: |
            **/*.txt

      - name: Create matrixes
        run: |
          echo "modified_matrix={\"file\": ${{ steps.files.outputs.all_changed_and_modified_files }}}" >> $GITHUB_OUTPUT
          echo "deleted_matrix={\"file\": ${{ steps.files.outputs.deleted_files }}}" >> $GITHUB_OUTPUT

  modified:
    needs: pushed
    if: needs.pushed.outputs.any_modified
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.pushed.outputs.modified_matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print file
        run: |
          echo "Printing file ${{ matrix.file }}"
          cat ${{ matrix.file }}

  deleted:
    needs: pushed
    if: needs.pushed.outputs.any_deleted
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.pushed.outputs.deleted_matrix) }}

    steps:
      - name: Print file
        run: |
          echo "File ${{ matrix.file }} has been deleted"
