name: Do something after merge

on:
  push:
    branches:
      - main

jobs:
  pushed:
    runs-on: ubuntu-latest
    outpus:
      docs: ${{ steps.files.outputs.all_changed_and_modified_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # With the default value of 1, there are corner cases where tj-actions/changed-files
          # fails with a `no merge base` error
          fetch-depth: 0

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.txt

  matrixed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ needs.pushed.outputs.docs }}

    steps:
      - name: Print file
        run: |
          echo "Printing file ${{ matrix.file }}"
          cat ${{ matrix.file }}
