name: Do things

on:
  # workflow_dispatch event allows the workflow to be triggered manually.
  # This could be used to run an immediate check after updating certificate secrets.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set env var
        run: |
          # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "FILES=\"\"$(ls -m ${{ github.workspace }}| sed 's/, /","/')\"\" >> $GITHUB_ENV

      - name: Get files list
        id: get-files
        run: |

          JSON=$(echo "[${{ join(env.FILES) }}]" | jq -c '[{"file": .[]}]')

          echo "::set-output name=files::{\"include\": $JSON }"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.files)}}
    steps:
      - run: |
          echo ${{ matrix.file }}
