name: Do things

on:
  # workflow_dispatch event allows the workflow to be triggered manually.
  # This could be used to run an immediate check after updating certificate secrets.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "::setFailed 'Shit's broken yo'"

      - name: Will never run
        run: echo "You'll never see this message"
