name: Do things

on:
  workflow_dispatch:
  push:
    branch:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
