name: Do things

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Test something else
        run: |
          echo '{
            "blocks": [
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4",
                    "alt_text": "Actor"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*<https://github.com/${{ github.actor }}|${{ github.actor }}>*"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Job ${{ github.job }} in workflow <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/workflow/|${{ github.workflow }}>"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Triggered by ${{ github.event_name }} for ${{ github.ref_type }} `${{ github.ref_name }}`"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "image",
                    "image_url": "https://github.githubassets.com/favicons/favicon.png",
                    "alt_text": "Github logo"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/|${{ github.repository }}> Run <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/|#${{ github.run_number }} | Attempt #${{ github.run_attempt }}>"
                  }
                ]
              }
            ]
          }'
