name: Do things

on:
  # workflow_dispatch event allows the workflow to be triggered manually.
  # This could be used to run an immediate check after updating certificate secrets.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        run: echo "FOO"

      - name: Notify Slack of something
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: "#general"
          config: .github/config/slack.yml
