name: Do things

on:
  # workflow_dispatch event allows the workflow to be triggered manually.
  # This could be used to run an immediate check after updating certificate secrets.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v34

      - name: List all changed files
        run: |
          echo "This is ${{ github.event_name == 'pull_request' && 'a PR' || 'master' }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
