name: Do things

on:
  # workflow_dispatch event allows the workflow to be triggered manually.
  # This could be used to run an immediate check after updating certificate secrets.
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:
      - name: Get files list
        id: get-files
        run: |
          FILES=$(ls ${{ github.workspace }} | xarg)
          JSON=$(echo "[${{ join($FILES, \",\") }}]" | jq -c '[{"file": .[]}]')

          echo "::set-output name=files::{\"include\": $JSON }"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.files)}}
    steps:
      - run: |
          echo ${{ matrix.file }}
