name: Do things

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do stuff
        run: echo "FOO"

      - name: Notify Slack of something
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # VERSION:
        if: always()
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: "#general"
          config: .github/config/slack.yml
