name: On PR

on:
  pull_request_target:

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Echo base
        run: echo ${{ github.base_ref }}

      - name: Checkout HEAD commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Echo head
        run: echo ${{ github.ref }}
